apiVersion: v1
kind: Service
metadata:
  name: spring-svc
  labels:
    app: spring-pod
spec:
  type: LoadBalancer
  selector:
    app: spring-pod
  ports:
    - name: http-metrics # IMPORTANT: Name the port for ServiceMonitor
      port: 80
      targetPort: 8084