apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-tasker
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/2016mehrab/argocd-practice
    targetRevision: HEAD
    path: simple-spring-boot-app
  destination:
    server: https://kubernetes.default.svc
    namespace: spring-tasker
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

#   argocd polls every 3 minutes
    automated:
      selfHeal: true
      prune: true